# common base image for development and 
FROM node:18 AS base
WORKDIR /app

# dev image contains everything needed for testing, development and building
FROM base AS development
COPY . /app

# install all dependencies and add source code
RUN npm install
RUN npm install -g @angular/cli@7.3.9

# builder runs unit tests and linter, then builds production code 
FROM development as builder
RUN npm run build:ssr:shop --prod --output-path=dist
# RUN ls -ls ../
# RUN ls -ls .
# RUN pwd

# release includes bare minimum required to run the app, copied from builder
FROM base AS shop
COPY --from=builder /app/dist/shop /app/dist/shop
COPY --from=builder /app/package.json /app/

ENV NODE_ENV "production"
ENV PORT 3001

EXPOSE 3001
CMD ["npm", "run", "serve:ssr:shop"]
